[package]
name = "feature4qi"
version = "0.1.0"
edition = "2024"

[lib]
name = "feature4qi"
path = "src/lib.rs"

[dependencies]
log = "0.4.27"

[dev-dependencies]
mockall = "0.13.1"
ctor = "0.5.0"
env_logger = "0.11.8"